POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MGQ3YmRiMTFmMjk2MWQ1NzgzZjViMyIsImlhdCI6MTcyOTAxMzY3MSwiZXhwIjoxNzI5MDE3MjcxfQ.QaNHicSTtGpcibF3OU1u9fnM5zxbmVnR99n2e9Hyd1g

{
    "title": "Title",
    "author": "Author",
    "url": "http://www.url.com",
    "likes": 5
}